### ISSUE TITLE
Script folders

### ISSUE THREAD

**Issue by AliAlnuaimi** [JMcKiern/warhawk-reversing#6]
Hi All,

what file format stores the script files? (as far as i see all the files are related to movies, sound, models, textures... but what about the scripts?

Thanks

**Comment by JMcKiern** [comment]
Hi @AliAlnuaimi,

All the code would be in the EBOOT.bin/EBOOT.elf file.

**Comment by AliAlnuaimi** [comment]
> Hi @AliAlnuaimi,
> 
> All the code would be in the EBOOT.bin/EBOOT.elf file.

Would it be possible to reverse engineer it?

**Comment by JMcKiern** [comment]
> Would it be possible to reverse engineer it?

Theoretically yes. But it was be extremely difficult and time consuming
